<a href="https://colab.research.google.com/github/jahnavireddyn/Hospital-Charges-Dataset/blob/main/Hospital_charges_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Hospital Charges Dataset Analysis

### This paper gives an insight of how we can store any hospital data digitally like hospital’s data records, payment records and how we can generate useful information from these records by using data analytics techniques.This dataset is focused on Hospital charges in The United States of America.This data is analyzed using python and pandas along with various other libraries for real time analysis and EDA as well.According to data analytics in healthcare informatics-The use of data analytics to enormous amounts of healthcare data collected on a daily basis has opened up a slew of new potential in recent years which allows for improvements in decision-making.At the business level it can lower costs and simplify internal operations and more.

### Analysis in this dataset is done on 12 columns namely DRG Definition- Design and development of the Diagnosis  Related Group (a patient classification scheme which provides a means of relating the type of patients a hospital treats to the costs incurred by the hospital) Provider Id, Provider Name–Name of the hospital, Provider Street Address –Address of the hospital, Provider City, Provider State, Provider Zipcode, Hospital Referral Region Description, Total Discharges, Average Covered Charges, Average Total Payments, Average Medicare Payments containing 163066 rows.

### This notebook provides data visualizations for :Most expensive treatments,Rank by cost at each state,Shows cheaper providers that are available within the state,Normalized distribution of inpatients across treatments.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#importing pandas library
import pandas as pd 
#importing numpy library
import numpy as np

In [ ]:
#importing csv file hospital_charges

data = pd.read_csv('/content/drive/MyDrive/EDA PRO/hospital_charges.csv')  
data

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,91,$32963.07,$5777.24,$4763.73
1,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,AL - Birmingham,14,$15131.85,$5787.57,$4976.71
2,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,AL - Birmingham,24,$37560.37,$5434.95,$4453.79
3,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,AL - Birmingham,25,$13998.28,$5417.56,$4129.16
4,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,AL - Birmingham,18,$31633.27,$5658.33,$4851.44
...,...,...,...,...,...,...,...,...,...,...,...,...
163060,948 - SIGNS & SYMPTOMS W/O MCC,670041,SETON MEDICAL CENTER WILLIAMSON,201 SETON PARKWAY,ROUND ROCK,TX,78664,TX - Austin,23,$26314.39,$3806.86,$3071.39
163061,948 - SIGNS & SYMPTOMS W/O MCC,670055,METHODIST STONE OAK HOSPITAL,1139 E SONTERRA BLVD,SAN ANTONIO,TX,78258,TX - San Antonio,11,$21704.72,$4027.36,$2649.72
163062,948 - SIGNS & SYMPTOMS W/O MCC,670056,SETON MEDICAL CENTER HAYS,6001 KYLE PKWY,KYLE,TX,78640,TX - Austin,19,$39121.73,$5704.36,$4058.36
163063,948 - SIGNS & SYMPTOMS W/O MCC,670060,TEXAS REGIONAL MEDICAL CENTER AT SUNNYVALE,231 SOUTH COLLINS ROAD,SUNNYVALE,TX,75182,TX - Dallas,11,$28873.09,$7663.09,$6848.54
163064,948 - SIGNS & SYMPTOMS W/O MCC,670068,TEXAS HEALTH PRESBYTERIAN HOSPITAL FLOWER MOUND,4400 LONG PRAIRIE ROAD,FLOWER MOUND,TX,75028,TX - Dallas,12,$15042.00,$3539.75,$2887.41

In [ ]:
#previewing first 5 rows of the data

data.head()

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,91,$32963.07,$5777.24,$4763.73
1,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,AL - Birmingham,14,$15131.85,$5787.57,$4976.71
2,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,AL - Birmingham,24,$37560.37,$5434.95,$4453.79
3,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10011,ST VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,AL - Birmingham,25,$13998.28,$5417.56,$4129.16
4,039 - EXTRACRANIAL PROCEDURES W/O CC/MCC,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,AL - Birmingham,18,$31633.27,$5658.33,$4851.44

In [ ]:
#viewing last 5 rows of the data

data.tail()

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
163060,948 - SIGNS & SYMPTOMS W/O MCC,670041,SETON MEDICAL CENTER WILLIAMSON,201 SETON PARKWAY,ROUND ROCK,TX,78664,TX - Austin,23,$26314.39,$3806.86,$3071.39
163061,948 - SIGNS & SYMPTOMS W/O MCC,670055,METHODIST STONE OAK HOSPITAL,1139 E SONTERRA BLVD,SAN ANTONIO,TX,78258,TX - San Antonio,11,$21704.72,$4027.36,$2649.72
163062,948 - SIGNS & SYMPTOMS W/O MCC,670056,SETON MEDICAL CENTER HAYS,6001 KYLE PKWY,KYLE,TX,78640,TX - Austin,19,$39121.73,$5704.36,$4058.36
163063,948 - SIGNS & SYMPTOMS W/O MCC,670060,TEXAS REGIONAL MEDICAL CENTER AT SUNNYVALE,231 SOUTH COLLINS ROAD,SUNNYVALE,TX,75182,TX - Dallas,11,$28873.09,$7663.09,$6848.54
163064,948 - SIGNS & SYMPTOMS W/O MCC,670068,TEXAS HEALTH PRESBYTERIAN HOSPITAL FLOWER MOUND,4400 LONG PRAIRIE ROAD,FLOWER MOUND,TX,75028,TX - Dallas,12,$15042.00,$3539.75,$2887.41

In [ ]:
# Checking the Shape of the dataset

numberofrows_1, numberofcolumns_1 = data.shape
print('There are {} rows and {} columns'.format(numberofrows_1, numberofcolumns_1)+' in our Dataset.')

There are 163065 rows and 12 columns in our Dataset.

In [ ]:
# Information about the datatypes and columns

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163065 entries, 0 to 163064
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   DRG Definition                        163065 non-null  object
 1   Provider Id                           163065 non-null  int64
 2   Provider Name                         163065 non-null  object
 3   Provider Street Address               163065 non-null  object
 4   Provider City                         163065 non-null  object
 5   Provider State                        163065 non-null  object
 6   Provider Zip Code                     163065 non-null  int64
 7   Hospital Referral Region Description  163065 non-null  object
 8    Total Discharges                     163065 non-null  int64
 9    Average Covered Charges              163065 non-null  object
 10   Average Total Payments               163065 non-null  object
 11  Average Medicare Payments             163065 non-null  object
dtypes: int64(3), object(9)
memory usage: 14.9+ MB

In [ ]:
# generating descriptive statistics for overview

data.describe()

         Provider Id  Provider Zip Code   Total Discharges
count  163065.000000      163065.000000       163065.000000
mean   255569.865428       47938.121908           42.776304
std    151563.671767       27854.323080           51.104042
min     10001.000000        1040.000000           11.000000
25%    110092.000000       27261.000000           17.000000
50%    250007.000000       44309.000000           27.000000
75%    380075.000000       72901.000000           49.000000
max    670077.000000       99835.000000         3383.000000

In [ ]:
#listing all the coloumn names
data.columns

Index(['DRG Definition', 'Provider Id', 'Provider Name',
       'Provider Street Address', 'Provider City', 'Provider State',
       'Provider Zip Code', 'Hospital Referral Region Description',
       ' Total Discharges ', ' Average Covered Charges ',
       ' Average Total Payments ', 'Average Medicare Payments'],
      dtype='object')

In [ ]:
#visualizing the null values in the dataset
data.isnull()

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
163060,False,False,False,False,False,False,False,False,False,False,False,False
163061,False,False,False,False,False,False,False,False,False,False,False,False
163062,False,False,False,False,False,False,False,False,False,False,False,False
163063,False,False,False,False,False,False,False,False,False,False,False,False
163064,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#finding the number of null values in each column
data.isnull().sum()

DRG Definition                          0
Provider Id                             0
Provider Name                           0
Provider Street Address                 0
Provider City                           0
Provider State                          0
Provider Zip Code                       0
Hospital Referral Region Description    0
 Total Discharges                       0
 Average Covered Charges                0
 Average Total Payments                 0
Average Medicare Payments               0
dtype: int64

In [ ]:
Value_Missing = data.isnull().sum().sort_values(ascending = False)
print(Value_Missing)
percent_missing = (data.isnull().sum() * 100 / len(data)).round(2).sort_values(ascending = False)
print(percent_missing)

DRG Definition                          0
Provider Id                             0
Provider Name                           0
Provider Street Address                 0
Provider City                           0
Provider State                          0
Provider Zip Code                       0
Hospital Referral Region Description    0
 Total Discharges                       0
 Average Covered Charges                0
 Average Total Payments                 0
Average Medicare Payments               0
dtype: int64
DRG Definition                          0.0
Provider Id                             0.0
Provider Name                           0.0
Provider Street Address                 0.0
Provider City                           0.0
Provider State                          0.0
Provider Zip Code                       0.0
Hospital Referral Region Description    0.0
 Total Discharges                       0.0
 Average Covered Charges                0.0
 Average Total Payments                 0.0
Average Medicare Payments               0.0
dtype: float64

In [ ]:
# Generate count statistics of duplicate entries

if (len(data[data.duplicated()]) > 0):
    print('No. of duplicated entries: ', len(data[data.duplicated()]))
    print(data[data.duplicated(keep = False)].sort_values(by = list(data.columns)).head())
else:
    print('No duplicated entries found.')

No duplicated entries found.

In [ ]:
#Finding the duplicate values in the dataset

In [ ]:
# Unique values of all features

data.nunique().to_frame(name = 'Unique Values')

                                      Unique Values
DRG Definition                                  100
Provider Id                                    3337
Provider Name                                  3201
Provider Street Address                        3326
Provider City                                  1977
Provider State                                   51
Provider Zip Code                              3053
Hospital Referral Region Description            306
 Total Discharges                               642
 Average Covered Charges                     160236
 Average Total Payments                      147842
Average Medicare Payments                    150328

In [ ]:
#importing seaborn library
import seaborn as sns
#importing matplot library
import matplotlib.pyplot as plt

In [ ]:
data['Average Medicare Payments']

0         $4763.73
1         $4976.71
2         $4453.79
3         $4129.16
4         $4851.44
            ...
163060    $3071.39
163061    $2649.72
163062    $4058.36
163063    $6848.54
163064    $2887.41
Name: Average Medicare Payments, Length: 163065, dtype: object

In [ ]:
data['Average Medicare Payments'] = data['Average Medicare Payments'].str.strip("$")

In [ ]:
data['Average Medicare Payments']

0         4763.73
1         4976.71
2         4453.79
3         4129.16
4         4851.44
           ...
163060    3071.39
163061    2649.72
163062    4058.36
163063    6848.54
163064    2887.41
Name: Average Medicare Payments, Length: 163065, dtype: object

In [ ]:
data['Average Covered Charges'] = data['Average Covered Charges'].str.strip("$")

KeyError: 'Average Covered Charges'

In [ ]:
data["Average Covered Charges"]

KeyError: 'Average Covered Charges'

In [ ]:
sns.boxplot(data['Average Medicare Payments'])

C:\Users\ASUS\anaconda3\lib\site-packages\seaborn\_decorators.py:36: FutureWarning: Pass the following variable as a keyword arg: x. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(

TypeError: Horizontal orientation requires numeric `x` variable.